sudo: false
language: node_js
node_js:
- '10'
- '12'
- '14'
- '15'
env:
  global:
  - BUILD_TIMEOUT=10000
before_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then chmod +x ./cc-test-reporter; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter before-build; fi
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
deploy:
  provider: npm
  email: alberto@berriart.com
  api_key:
    secure: 4WgbsyUh3tQEaxtMiob1N95lcg1IEAXyvyNhfHZYeojjFj5vlikei5uxI1TNsEfOWwmlk6qr94bPNe28CAahV8BkDWV9V8xugphxx6PBhPPDjsaYCwnpT72jh9wLBYQDjAsRPHZoAgLeP6YZUJGeqcmsHyK3bV/V/n7bU1vwWD36dL7uoNuScon9rTnGXfLdtymhnzOOg8tiAc4+7qkevR0NUbCxbq+fPpgPDv7/9y/kjDPSljOXasHuPjfaMMsYr8hG6ZmRyIm2+qAd4H+MN56Ry7FRsIktUxQ3Mil5Su+S8EXi1Dx3HoskmK5Y4UMgRWNkuESEiiSkNKd9InHg2jozAHrjoalcw7rtalNhW78G+LOoSqozpEEP06iK8j71tBFmD+XlLxyGIwOBUkR4JscBf6qk/+n/SOnseTKu1HVFCNggM5JDlDi5PzcSS0KNe7TADX8S89rKpVL1RIP0oLCPtd0FKd94MnDjnOpNTbYI8X42R575FuB0YHisx6LrQZ3EC7b5tEDB8jZJiO5dQCynjomeJieXpIDGoyknjD4HBOeyOfg1Y51zN5NsmPK29OAbsi6C2nnLtVe5Br9F4lvk0zkTdONuHbc0fYcfK6cXDmJvv+JpoFwlB1Q6V7uNhUF4qDgJfebE+WA9SZFlmapUApg+Eumv3m2gZtw7VLs=
  on:
    tags: true
    repo: artberri/rollup-plugin-istanbul
