name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node:
        description: "Node version"
        required: true
        default: 20.x
        type: choice
        options:
          - 16.x
          - 18.x
          - 20.x
      rollup:
        description: "Rollup version"
        required: true
        default: ^4
        type: choice
        options:
          - ^1
          - ^2
          - ^3
          - ^4

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        rollup-version: [^1, ^2, ^3]
        include:
          - node-version: 18.x
            rollup-version: ^4
          - node-version: 20.x
            rollup-version: ^4

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: "8.x"
          run_install: false
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Lint code
        run: pnpm run lint
      - name: Install rollup version {{ matrix.rollup-version }}
        run: pnpm add -D rollup@${{ matrix.rollup-version }}
      - name: Test code
        run: pnpm run test
